//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cortex.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cortex.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Cortex.Net] Actions should have valid names, got nothing, autogenerating name..
        /// </summary>
        internal static string ActionNameNull {
            get {
                return ResourceManager.GetString("ActionNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The derivation ({0}) was already added to the set of observers of observable ({1}).
        /// </summary>
        internal static string AlreadyAddedObserverToObservable {
            get {
                return ResourceManager.GetString("AlreadyAddedObserverToObservable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BindDependencies expects a DependenciesState != ({0}).
        /// </summary>
        internal static string BindDependenciesExpectsStateNonEqual {
            get {
                return ResourceManager.GetString("BindDependenciesExpectsStateNonEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to assign a new value to this computed value ({0}).
        /// </summary>
        internal static string CannotAssignComputedValue {
            get {
                return ResourceManager.GetString("CannotAssignComputedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot trace an object that is not an observable Object..
        /// </summary>
        internal static string CannotTraceNotObservable {
            get {
                return ResourceManager.GetString("CannotTraceNotObservable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only tracking IDerivation instances can be added with a DependenciesState != ({0}).
        /// </summary>
        internal static string CanOnlyAddTrackedDependencies {
            get {
                return ResourceManager.GetString("CanOnlyAddTrackedDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caught an exception during a get operation. Inspect the inner exception for details..
        /// </summary>
        internal static string CaughtExceptionDuringGet {
            get {
                return ResourceManager.GetString("CaughtExceptionDuringGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computed values are not allowed to cause side effects by changing observables that are already being observed. Tried to modify: ({0}).
        /// </summary>
        internal static string ComputedValuesAreNotAllowedToCauseSideEffects {
            get {
                return ResourceManager.GetString("ComputedValuesAreNotAllowedToCauseSideEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle detected in computation ({0}): {1}.
        /// </summary>
        internal static string CycleDetectedInComputation {
            get {
                return ResourceManager.GetString("CycleDetectedInComputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setter of computed value ({0}) is trying to update itself. Did you intend to update an observable value instead of a computed value?.
        /// </summary>
        internal static string CycleDetectedInSetter {
            get {
                return ResourceManager.GetString("CycleDetectedInSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get expression is null for ({0}) of type ({1}).
        /// </summary>
        internal static string GetExpressionNull {
            get {
                return ResourceManager.GetString("GetExpressionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global unobservation should only be queued without observers..
        /// </summary>
        internal static string GlobalUnobservationOnlyWithoutObservers {
            get {
                return ResourceManager.GetString("GlobalUnobservationOnlyWithoutObservers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid action stack. did you forget to finish an action?.
        /// </summary>
        internal static string InvalidActionStack {
            get {
                return ResourceManager.GetString("InvalidActionStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Cortex.Net] ({0}) is invalidated due to change in ({1}).
        /// </summary>
        internal static string InvalidatedDueToChange {
            get {
                return ResourceManager.GetString("InvalidatedDueToChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) is null..
        /// </summary>
        internal static string IsNull {
            get {
                return ResourceManager.GetString("IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side effects like changing state are not allowed at this point. Are you trying to modify state from, for example, the render function of a React component? Tried to modify: ({0}).
        /// </summary>
        internal static string ModifiedOutsideAction {
            get {
                return ResourceManager.GetString("ModifiedOutsideAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action` if this change is intended. Tried to modify: ({0}).
        /// </summary>
        internal static string ModifiedOutsideActionEnforceAlways {
            get {
                return ResourceManager.GetString("ModifiedOutsideActionEnforceAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The derivation ({0}) does not exist in the set of observers of observable ({1}).
        /// </summary>
        internal static string ObserverNotInObservable {
            get {
                return ResourceManager.GetString("ObserverNotInObservable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) should only be called when the shared state is in batch mode..
        /// </summary>
        internal static string OnlyInBatch {
            get {
                return ResourceManager.GetString("OnlyInBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property or method with name ({0}) allready exists on object with name ({1}).
        /// </summary>
        internal static string PropertyOrMethodAlreadyExistOnObservableObject {
            get {
                return ResourceManager.GetString("PropertyOrMethodAlreadyExistOnObservableObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property or method with name ({0}) not found on object with name ({1}).
        /// </summary>
        internal static string PropertyOrMethodNotFoundOnObservableObject {
            get {
                return ResourceManager.GetString("PropertyOrMethodNotFoundOnObservableObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided expression ({0}) to trace is not a member expression..
        /// </summary>
        internal static string ProvidedExpressionNoMemberExpression {
            get {
                return ResourceManager.GetString("ProvidedExpressionNoMemberExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided member with name ({0}) is no derivation (like a reaction or a computed value).
        /// </summary>
        internal static string ProvidedMemberNoDerivation {
            get {
                return ResourceManager.GetString("ProvidedMemberNoDerivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reaction doesn&apos;t converge to a stable state after ({0}) iterations. Probably there is a cycle in the reactive function: ({1}).
        /// </summary>
        internal static string ReactionDoesNotConverge {
            get {
                return ResourceManager.GetString("ReactionDoesNotConverge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Cortex.Net] ({0}) is read outside a reactive context..
        /// </summary>
        internal static string ReadOutsideReaction {
            get {
                return ResourceManager.GetString("ReadOutsideReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Cortex.Net] ({0}) is read outside a reactive context. Doing full recompute..
        /// </summary>
        internal static string ReadOutsideReactionRecompute {
            get {
                return ResourceManager.GetString("ReadOutsideReactionRecompute", resourceCulture);
            }
        }
    }
}
